Flask学习/blueprints/displaydata.py
from flask import Blueprint, render_template,request
from models import NewHouseModel, OldHouseModel,UserModel
from .forms import SearchForm
from decorators import login_required

bp = Blueprint('displayinfo', __name__, url_prefix='/displayinfo')


@bp.route('/newhouseinfo')
@login_required
def dispaly_newhouseinfo():
    newhouse_info = NewHouseModel.query.all()
    # 面积正序
    area_asc = NewHouseModel.query.order_by((NewHouseModel.area + 0)).all()
    # 面积倒序
    area_desc = NewHouseModel.query.order_by((NewHouseModel.area + 0).desc()).all()
    # 均价正序
    avg_asc = NewHouseModel.query.order_by((NewHouseModel.avgprice + 0)).all()
    # 均价倒序
    avg_desc = NewHouseModel.query.order_by((NewHouseModel.avgprice + 0).desc()).all()
    # 总价正序
    total_asc = NewHouseModel.query.order_by((NewHouseModel.totalprice+0)).all()
    # 总价倒序
    total_desc = NewHouseModel.query.order_by((NewHouseModel.totalprice+0).desc()).all()
    return render_template('user_nh_displaydata.html', newhouse_info=newhouse_info, area_asc=area_asc,area_desc=area_desc,avg_asc=avg_asc, avg_desc=avg_desc,total_asc=total_asc,total_desc=total_desc)

@bp.route('/adminnewhouseinfo')
def dispaly_adminnewhouseinfo():
    newhouse_info = NewHouseModel.query.all()
    # 面积正序
    area_asc = NewHouseModel.query.order_by((NewHouseModel.area + 0)).all()
    # 面积倒序
    area_desc = NewHouseModel.query.order_by((NewHouseModel.area + 0).desc()).all()
    # 均价正序
    avg_asc = NewHouseModel.query.order_by((NewHouseModel.avgprice + 0)).all()
    # 均价倒序
    avg_desc = NewHouseModel.query.order_by((NewHouseModel.avgprice + 0).desc()).all()
    # 总价正序
    total_asc = NewHouseModel.query.order_by((NewHouseModel.totalprice+0)).all()
    # 总价倒序
    total_desc = NewHouseModel.query.order_by((NewHouseModel.totalprice+0).desc()).all()
    return render_template('admin_newhouse_display.html', newhouse_info=newhouse_info, area_asc=area_asc,area_desc=area_desc,avg_asc=avg_asc, avg_desc=avg_desc,total_asc=total_asc,total_desc=total_desc)

@bp.route('/oldhouseinfo')
def display_oldhouseinfo():
    oldhouse_info = OldHouseModel.query.all()
    #建造年份正序
    year_asc = OldHouseModel.query.order_by((OldHouseModel.year+0)).all()
    #建造年份倒序
    year_desc = OldHouseModel.query.order_by((OldHouseModel.year+0).desc()).all()
    # 面积正序
    area_asc = OldHouseModel.query.order_by((OldHouseModel.area + 0)).all()
    # 面积倒序
    area_desc = OldHouseModel.query.order_by((OldHouseModel.area + 0).desc()).all()
    # 均价正序
    avg_asc = OldHouseModel.query.order_by((OldHouseModel.avgprice + 0)).all()
    # 均价倒序
    avg_desc = OldHouseModel.query.order_by((OldHouseModel.avgprice + 0).desc()).all()
    # 总价正序
    total_asc = OldHouseModel.query.order_by((OldHouseModel.totalprice+0)).all()
    # 总价倒序
    total_desc = OldHouseModel.query.order_by((OldHouseModel.totalprice+0).desc()).all()
    return render_template('user_oh_displaydata.html', oldhouse_info=oldhouse_info,year_asc=year_asc,year_desc=year_desc,area_asc=area_asc,area_desc=area_desc,avg_asc=avg_asc,avg_desc=avg_desc,total_asc=total_asc,total_desc=total_desc)

@bp.route('/adminoldhouseinfo')
def display_adminoldhouseinfo():
    oldhouse_info = OldHouseModel.query.all()
    #建造年份正序
    year_asc = OldHouseModel.query.order_by((OldHouseModel.year+0)).all()
    #建造年份倒序
    year_desc = OldHouseModel.query.order_by((OldHouseModel.year+0).desc()).all()
    # 面积正序
    area_asc = OldHouseModel.query.order_by((OldHouseModel.area + 0)).all()
    # 面积倒序
    area_desc = OldHouseModel.query.order_by((OldHouseModel.area + 0).desc()).all()
    # 均价正序
    avg_asc = OldHouseModel.query.order_by((OldHouseModel.avgprice + 0)).all()
    # 均价倒序
    avg_desc = OldHouseModel.query.order_by((OldHouseModel.avgprice + 0).desc()).all()
    # 总价正序
    total_asc = OldHouseModel.query.order_by((OldHouseModel.totalprice+0)).all()
    # 总价倒序
    total_desc = OldHouseModel.query.order_by((OldHouseModel.totalprice+0).desc()).all()
    return render_template('admin_oldhouse_display.html', oldhouse_info=oldhouse_info,year_asc=year_asc,year_desc=year_desc,area_asc=area_asc,area_desc=area_desc,avg_asc=avg_asc,avg_desc=avg_desc,total_asc=total_asc,total_desc=total_desc)

@bp.route('/userdata')
def display_userdata():
    userdata = UserModel.query.all()
    return render_template('userdata_display.html',userdata=userdata)

# 搜索框视图函数
'''
有新房数据和二手房数据,当使用搜索框功能的时候,无法设置筛选的哪个房型的数据,就是一个search函数接收两个房型数据的话,如何判断要搜索哪个房型的数据呢?
'''
@bp.route('/newsearch')
def search_new():
    q = request.args.get('q')
    print(q)
    newhouseinfo = NewHouseModel.query.filter(NewHouseModel.housename.contains(q)).all()
    print(newhouseinfo)
    return render_template('user_nh_displaydata.html',newhouseinfo=newhouseinfo)

@bp.route('/oldsearch')
def search_old():
    q = request.args.get('q')
    oldhouseinfo = OldHouseModel.query.filter(OldHouseModel.housename.contains(q)).all()
    return render_template('user_oh_displaydata.html',oldhouseinfo=oldhouseinfo)

Flask学习/blueprints/user.py
# 组织 Flask 应用的代码：将相关的功能模块集中在一起，便于维护。
# 定义应用的 URL：蓝图可以定义自己的 URL，然后将视图函数与 URL 绑定起来。



from flask import Blueprint,render_template,redirect,url_for,request,session
# from flask_sqlalchemy import SQLAlchemy
from .forms import RegisterForm,LoginForm
from models import UserModel,AdminModel
from exts import db



bp = Blueprint('user',__name__,url_prefix='/user')


@bp.route('/login', methods=['GET','POST'])
def login():#用户登录
    form = LoginForm(request.form)
    if request.method == 'GET':
        print('请求方式为GET')
        return render_template('userlogin.html',form=form)
    else:
        print('请求方式为POST')
        if form.validate():
            print('数据验证通过')
            username = form.username.data
            password = form.password.data
            user = UserModel.query.filter_by(username=username).first()
            if not user:
                print('用户名在数据库中不存在')
                return redirect('/user/login')
            elif user.password == password:
                session['user_id'] = user.id
                if username == 'admin':
                    return redirect('/displayinfo/adminnewhouseinfo')
                else:
                    return redirect('/displayinfo/newhouseinfo')
            else:
                print('密码输入错误！')
                return redirect('/user/login')
        else:
            print('数据验证不通过')
            print(form.errors)
            return render_template('userlogin.html',form=form)

@bp.route('/adminlogin', methods=['GET','POST'])
def adminlogin():#管理员登录
    form = LoginForm(request.form)
    if request.method == 'GET':
        print('gly请求方式为GET')
        return render_template('admin_login.html',form=form)
    else:
        print('gly请求方式为POST')
        if form.validate():
            print('gly数据验证通过')
            username = form.username.data
            password = form.password.data
            user = AdminModel.query.filter_by(adminname=username).first()
            if not user:
                print('管理员在数据库中不存在')
                return redirect('/user/adminlogin')
            elif user.password == password:
                # print('[][][][]')
                session['admin_id'] = user.id
                return redirect('/displayinfo/adminnewhouseinfo')
            else:
                print('gly密码输入错误！')
                return redirect('/user/adminlogin')
        else:
            print('gly数据验证不通过')
            print(form.errors)
            return render_template('admin_login.html',form=form)


@bp.route('/register', methods=['GET','POST'])
def register():#注册
    form = RegisterForm(request.form)
    if request.method == "GET":
        print('请求方法为GET')
        return render_template('register.html', form=form)
    else:#request.method == "POST"
        print('请求方法为POST')
        if form.validate():  # 如果验证通过 # 获取数据
            username = form.username.data
            password = form.password.data
            check_password = form.check_password.data
            print(username, password, check_password)
            judgement = UserModel.query.filter_by(username=username).first()
            if judgement:
                print('该用户已存在')
                return redirect('/user/register')
            else:
                user = UserModel(username=username,password=password)
                db.session.add(user)
                db.session.commit()
                return redirect('/user/login')
        else:
            print('数据验证不通过')
            print(form.errors)
            return render_template('register.html', form=form)

#退出登录
@bp.route('/logout')
def logout():
    session.clear()
    return redirect('/')

Flask学习/templates/base1.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/bootstrap.4.6.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/init.css') }}">
    {% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#">房产信息监测系统</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">首页 <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="http://127.0.0.1:5000/publishinfo/newhouseinfo" target="_blank">发布新房</a>
                    {#                    <seclect id="select3">#}
                    {#                        <option value="">发布房产信息</option>#}
                    {#                        <option value="http://127.0.0.1:5000/publishinfo/newhouseinfo">发布新房信息</option>#}
                    {#                        <option value="http://127.0.0.1:5000/publishinfo/oldhouseinfo">发布二手房信息</option>#}
                    {#                    </seclect>#}
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="http://127.0.0.1:5000/publishinfo/oldhouseinfo" target="_blank">发布二手房</a>
                </li>
{#                <li class="nav-item ml-2">#}
{#                    <form class="form-inline my-2 my-lg-0" method="GET" action="">#}
{#                        <input class="form-control mr-sm-2" type="search" placeholder="关键字" aria-label="Search"#}
{#                               name="q">#}
{#                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>#}
{#                    </form>#}
{#                </li>#}
                <li>
                    <form class="nav-item active">
                        <!-- <a class="nav-link" href="/">数据查看 <span class="sr-only">(current)</span></a> -->
                        <!-- <a class="nav-link" href="/">价格分析 <span class="sr-only">(current)</span></a> -->
                        <select name="data-view" id="select1">
                            <option value="">数据查看</option>
                            <option value="http://127.0.0.1:5000/displayinfo/adminnewhouseinfo" class="xinfang">新房</option>
                            <option value="http://127.0.0.1:5000/displayinfo/adminoldhouseinfo">二手房</option>
                        </select>
                        <select name="price-analysis" id="select2">
                            <option value="">价格分析</option>
                            <option value="http://127.0.0.1:5000/datavisualization/avgprice">均价分析</option>
                            <option value="http://127.0.0.1:5000/datavisualization/totalprice">总价分析</option>
                            <option value="http://127.0.0.1:5000/datavisualization/distribution">地区-房产数量分析</option>
                            <option value="http://127.0.0.1:5000/datavisualization/year">年份-房产建造数量分析</option>
                        </select>
                    </form>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="http://127.0.0.1:5000/displayinfo/userdata" target="_blank">用户数据管理</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if user %}
                    <li class="nav-item">
                        <span class="nav-link">{{ user.username }}</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.logout') }}">退出登录</a>
                    </li>
                {% elif admin %}
                    <li class="nav-item">
                        <span class="nav-link">{{ admin.adminname }}</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.logout') }}">退出登录</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.login') }}">用户登录</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.adminlogin') }}">管理员登录</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.register') }}">注册</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% block body %}{% endblock %}
</div>
</body>
<script>
    let pubSelect = document.querySelectorAll('#select3')
    let aSelect = document.querySelectorAll("#select1");
    let bSelect = document.querySelectorAll("#select2");
    {#console.log(aSelect);#}
    for (var x = 0; x < pubSelect.length; i++) {
        pubSelect[x].onchange = function () {
            var url = this.options[this.selectedIndex].value;
            if (url != '') {
                window.open(url);
            }
        }
    }
    for (var i = 0; i < aSelect.length; i++) {
        aSelect[i].onchange = function () {
            var url = this.options[this.selectedIndex].value;
            if (url != '') {
                window.open(url);
            }
        }
    }
    for (var j = 0; j < bSelect.length; j++) {
        bSelect[j].onchange = function () {
            var url = this.options[this.selectedIndex].value;
            if (url != '') {
                window.open(url);
            }
        }
    }
</script>

</html>

Flask学习/templates/base_new.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/bootstrap.4.6.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/init.css') }}">
    {% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
    {% block stytle %}{% endblock %}
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#">房产销售信息监测系统</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">首页 <span class="sr-only">(current)</span></a>
                </li>

{#                <li class="nav-item ml-2">#}
{#                    <form class="form-inline my-2 my-lg-0" method="GET"#}
{#                          action="{{ url_for('displayinfo.search_new') }}">#}
{#                        <input class="form-control mr-sm-2" type="search" placeholder="关键字" aria-label="Search"#}
{#                               name="q">#}
{#                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>#}
{#                    </form>#}
{#                </li>#}
                <li>
                    <form class="nav-item active">
                        <!-- <a class="nav-link" href="/">数据查看 <span class="sr-only">(current)</span></a> -->
                        <!-- <a class="nav-link" href="/">价格分析 <span class="sr-only">(current)</span></a> -->
                        <select name="data-view" id="select1">
                            <option value="">数据查看</option>
                            <option value="http://127.0.0.1:5000/displayinfo/newhouseinfo" class="xinfang">新房</option>
                            <option value="http://127.0.0.1:5000/displayinfo/oldhouseinfo">二手房</option>
                        </select>
                        <select name="price-analysis" id="select2">
                            <option value="">价格分析</option>
                            <option value="http://127.0.0.1:5000/datavisualization/avgprice">均价分析</option>
                            <option value="http://127.0.0.1:5000/datavisualization/totalprice">总价分析</option>
                            <option value="http://127.0.0.1:5000/datavisualization/distribution">地区-房产数量分析</option>
                            <option value="http://127.0.0.1:5000/datavisualization/year">年份-房产建造数量分析</option>
                        </select>
                    </form>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if user %}
                    <li class="nav-item">
                        <span class="nav-link">{{ user.username }}</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.logout') }}">退出登录</a>
                    </li>
                {% elif admin %}
                    <li class="nav-item">
                        <span class="nav-link">{{ admin.adminname }}</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.logout') }}">退出登录</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.login') }}">用户登录</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.adminlogin') }}">管理员登录</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.register') }}">注册</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% block body %}{% endblock %}
</div>
</body>
<script>
    let pubSelect = document.querySelectorAll('#select3')
    let aSelect = document.querySelectorAll("#select1");
    let bSelect = document.querySelectorAll("#select2");
    {#let search = document.querySelector('.btn');#}
    {#let tbody = document.querySelector('tbody');#}
    {#console.log(aSelect);#}
    for (var x = 0; x < pubSelect.length; i++) {
        pubSelect[x].onchange = function () {
            var url = this.options[this.selectedIndex].value;
            if (url != '') {
                window.open(url);
            }
        }
    }
    for (var i = 0; i < aSelect.length; i++) {
        aSelect[i].onchange = function () {
            var url = this.options[this.selectedIndex].value;
            if (url != '') {
                window.open(url);
            }
        }
    }
    for (var j = 0; j < bSelect.length; j++) {
        bSelect[j].onchange = function () {
            var url = this.options[this.selectedIndex].value;
            if (url != '') {
                window.open(url);
            }
        }
    }

    {#function btn() {#}
    {#    tbody.innerHTML = '';#}
    {#    {% for houseinfo in newhouseinfo %}#}
    {#        var tr = document.createElement('tr');#}
    {#        tr.innerHTML = '<td>{{ houseinfo.id }}</td><td>{{ houseinfo.housename }}</td><td>{{ houseinfo.developer }}</td><td>{{ houseinfo.location }}</td><td>{{ houseinfo.room }}</td><td>{{ houseinfo.ty }}</td><td>{{ houseinfo.tag }}</td><td>{{ houseinfo.area }}</td><td>{{ houseinfo.avgprice }}</td><td>{{ houseinfo.totalprice }}</td><td>{{ houseinfo.user_id }}</td>';#}
    {#        tbody.appendChild(tr);#}
    {#    {% endfor %}#}
    {#fgsd}#}
</script>

</html>

Flask学习/templates/base_old.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/bootstrap.4.6.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/init.css') }}">
    {% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
    {% block stytle %}{% endblock %}
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#">房产销售信息监测系统</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">首页 <span class="sr-only">(current)</span></a>
                </li>

{#                <li class="nav-item ml-2">#}
{#                    <form class="form-inline my-2 my-lg-0" method="GET" action="{{ url_for('displayinfo.search_old') }}">#}
{#                        <input class="form-control mr-sm-2" type="search" placeholder="关键字" aria-label="Search"#}
{#                               name="q">#}
{#                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>#}
{#                    </form>#}
{#                </li>#}
                <li>
                    <form class="nav-item active">
                        <!-- <a class="nav-link" href="/">数据查看 <span class="sr-only">(current)</span></a> -->
                        <!-- <a class="nav-link" href="/">价格分析 <span class="sr-only">(current)</span></a> -->
                        <select name="data-view" id="select1">
                            <option value="">数据查看</option>
                            <option value="http://127.0.0.1:5000/displayinfo/newhouseinfo" class="xinfang">新房</option>
                            <option value="http://127.0.0.1:5000/displayinfo/oldhouseinfo">二手房</option>
                        </select>
                        <select name="price-analysis" id="select2">
                            <option value="">价格分析</option>
                            <option value="http://127.0.0.1:5000/datavisualization/avgprice">均价分析</option>
                            <option value="http://127.0.0.1:5000/datavisualization/totalprice">总价分析</option>
                            <option value="http://127.0.0.1:5000/datavisualization/distribution">地区-房产数量分析</option>
                            <option value="http://127.0.0.1:5000/datavisualization/year">年份-房产建造数量分析</option>
                        </select>
                    </form>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if user %}
                    <li class="nav-item">
                        <span class="nav-link">{{ user.username }}</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.logout') }}">退出登录</a>
                    </li>
                {% elif admin %}
                     <li class="nav-item">
                        <span class="nav-link">{{ admin.adminname }}</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.logout') }}">退出登录</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.login') }}">用户登录</a>
                    </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.adminlogin') }}">管理员登录</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.register') }}">注册</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% block body %}{% endblock %}
</div>
</body>
<script>
    let pubSelect = document.querySelectorAll('#select3')
    let aSelect = document.querySelectorAll("#select1");
    let bSelect = document.querySelectorAll("#select2");
    {#console.log(aSelect);#}
    for (var x = 0; x < pubSelect.length; i++) {
        pubSelect[x].onchange = function () {
            var url = this.options[this.selectedIndex].value;
            if (url != '') {
                window.open(url);
            }
        }
    }
    for (var i = 0; i < aSelect.length; i++) {
        aSelect[i].onchange = function () {
            var url = this.options[this.selectedIndex].value;
            if (url != '') {
                window.open(url);
            }
        }
    }
    for (var j = 0; j < bSelect.length; j++) {
        bSelect[j].onchange = function () {
            var url = this.options[this.selectedIndex].value;
            if (url != '') {
                window.open(url);
            }
        }
    }
</script>

</html>

Flask学习/templates/index.html
{% extends 'base.html' %}

{% block title %}首页{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">
{% endblock %}
{% block body %}
    {#<h1>你好！这是首页</h1>#}

{% endblock %}

Flask学习/templates/oldhousepubinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{{url_for('static',filename='css/userlogin.css')}}">
</head>
<body>

{#    <form action="#" method="post">#}
{#        {{ form.csrf_token() }}#}
{#        {{ form.housename.label }}:{{ form.housename }}<br>#}
{#        {{ form.developer.label }}:{{ form.developer }}<br>#}
{#        {{ form.year.label }}:{{ form.year }}<br>#}
{#        {{ form.location.label }}:{{ form.location }}<br>#}
{#        {{ form.room.label }}:{{ form.room }}<br>#}
{#        {{ form.tag.label }}:{{ form.tag }}<br>#}
{#        {{ form.area.label }}:{{ form.area }}<br>#}
{#        {{ form.avgprice.label }}:{{ form.avgprice }}<br>#}
{#        {{ form.totalprice.label }}:{{ form.totalprice }}<br>#}
{#        <p>{{ form.submit() }}</p>#}
{#    </form>#}
<div class="box">
    <div class="login-box">
        <h1>发布二手房信息</h1>
        <form action="#" method="post">
            {{ form.csrf_token() }}
            <div class="user-box">
                {{ form.housename.label }}:{{ form.housename }}<br>
                <label for="">小区名称</label>
            </div>
            <div class="user-box">
                {{ form.year.label }}:{{ form.year }}<br>
                <label for="">建造年份</label>
            </div>
            <div class="user-box">
                {{ form.location.label }}:{{ form.location }}<br>
                <label for="">地址</label>
            </div>
            <div class="user-box">
                {{ form.room.label }}:{{ form.room }}<br>
                <label for="">几室几厅</label>
            </div>
            <div class="user-box">
                {{ form.tag.label }}:{{ form.tag }}<br>
                <label for="">房产标签</label>
            </div>
            <div class="user-box">
                {{ form.area.label }}:{{ form.area }}<br>
                <label for="">建筑面积</label>
            </div>
            <div class="user-box">
                {{ form.avgprice.label }}:{{ form.avgprice }}<br>
                <label for="">均价</label>
            </div>
            <div class="user-box">
                {{ form.totalprice.label }}:{{ form.totalprice }}<br>
                <label for="">总价</label>
            </div>
            <p>{{ form.submit() }}</p>
        </form>
    </div>
</div>
</body>
</html>